### ISSUE TITLE
Cannot install with vim-plug

### ISSUE THREAD

**Issue by elclanrs** [steelsojka/headwind.nvim#3]
I would love to try this plugin, but it doesn't work with [vim-plug](https://github.com/junegunn/vim-plug) because it expects the branch to be called "master".

<img width="411" alt="vim-plug-headwind" src="https://user-images.githubusercontent.com/1661925/124655982-999e7680-de6e-11eb-88c8-fcf235429b2c.png">

Please consider mirroring the `main` branch to `master` so it can work with vim-plug.

**Comment by steelsojka** [comment]
You can point vim-plug to use a specific branch. I suggest trying that.
This is in the vim-plug docs i believe

**Comment by elclanrs** [comment]
Thanks, I didn't realize that was an option. For reference:

```vim
Plug 'steelsojka/headwind.nvim', {'branch': 'main'}
```
